name: Report remaining open issues
on:
  push:
    branches: [ "main" ]
  schedule:
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
jobs:
  update_moderator:
    runs-on: ubuntu-latest
    environment: Workflow
    steps:
      - name: Collect information
        run: |
          numOpenIssues="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              repository(owner: $owner, name: $name) {
                issues(states:OPEN){
                  totalCount
                }
              }
            }
          ' --jq '.data.repository.issues.totalCount')"

          echo 'NUM_OPEN_ISSUES='$numOpenIssues >> $GITHUB_ENV
          echo 'Run attempt: '${{ github.run_attempt }}
          echo 'Run ID: '${{ github.run_id }}
          echo 'Run number: '${{ github.run_number }}
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_GH_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      - name: Get result
        run: |
          index=$((${{ env.MODERATOR_INDEX}} + 1))
          moderatorList=${{ env.MODERATOR_LIST }}
          max=$((${#moderatorList[@]} - 1))
          if (( $index > $max )); then index=0 fi
          echo 'Index: '$index
          echo 'Max: '$max
          echo 'Current: '${moderatorList[$index]}
        env:
          MODERATOR_INDEX: ${{ vars.MODERATOR_INDEX }}
          MODERATOR_LIST: ${{ vars.MODERATOR_LIST }}
      #- run: |
      #    gh issue create --title "Issue report" --body "$NUM_OPEN_ISSUES issues remaining" --repo $GITHUB_REPOSITORY
      #  env:
      #    GH_TOKEN: ${{ secrets.WORKFLOW_GH_TOKEN }}
