name: Report remaining open issues
on:
  push:
    branches: [ "main" ]
  schedule:
    # Every Sunday at 19:00 UTC
    - cron: '0 19 * * 0'
jobs:
  update_moderator:
    runs-on: ubuntu-latest
    environment: Workflow
    env:
        MODERATOR_INDEX: ${{ vars.MODERATOR_INDEX }}
        MODERATOR_LIST: ${{ vars.MODERATOR_LIST }}
    steps:
      - name: Calculate next moderator
        run: |
          index=$((${{ env.MODERATOR_INDEX }} + 1))
          moderatorList=${{ env.MODERATOR_LIST }}
          max=$((${#moderatorList[@]} - 1))
          if (( $index > $max )); then
            index=0
          fi
          next=${moderatorList[$index]}
          echo 'MODERATOR_INDEX='$index >> $GITHUB_ENV
          echo 'Index: '$index
          echo 'Max: '$max
          echo 'Next: '$next
          echo 'CURRENT_MODERATOR='$next >> $GITHUB_ENV
      - name: Update variables
        run: |
          gh variable set MODERATOR_INDEX --body "$MODERATOR_INDEX" --env Workflow --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_GH_TOKEN }}
      - name: Update report
        run: |
          gh issue edit 1 --title "Moderator report" --body "The current moderator is $CURRENT_MODERATOR." --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_GH_TOKEN }}
